# Stage 1 - the build process
FROM node:15.11.0-alpine as build-deps
WORKDIR /usr/src/app
COPY ["package.json", "yarn.lock", "webpack.config.js", "./"]
RUN yarn
COPY . ./
RUN yarn build

# Stage 2 - the production environment
FROM nginx:1.12-alpine
COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY --from=build-deps /usr/src/app/dist /usr/share/nginx/html
#EXPOSE 30090
CMD ["nginx", "-g", "daemon off;"]

